# Site settings

theme: jekyll-theme-cayman
title: Joel Pinheiro
email: joelcostapinheiro @ gmail . com
description: > # this means to ignore newlines until "baseurl:"
  Knowledge acquired in the short time of this life.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joelpinheiro.com" 
# the base hostname & protocol for your site
github_username:  joelcpinheiro
show_downloads: false
google_analytics: UA-63707839-2


