# Site settings

remote_theme: jekyll-shell-theme
title: Joel Pinheiro
email: joelcostapinheiro @ gmail . com
description: > # this means to ignore newlines until "baseurl:"
  Knowledge acquired in the short time of this life.
baseurl: "/joelcpinheiro.github.io" # the subpath of your site, e.g. /blog
url: "http://joelpinheiro.com" 
# the base hostname & protocol for your site
github_username:  joelcpinheiro
show_downloads: false
google_analytics: UA-63707839-2

baseurl: "/joelcpinheiro.github.io" # the subpath of your site
url: "https://joelpinheiro.com" # the base hostname & protocol for your site

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - tips.md
  - profile.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
